### ISSUE TITLE
Node.js Foundation Outreach Strategic Initiative Meeting 2019-04-16

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/outreach#13]
## Time

**UTC Tues 15-Apr-2019 16:00 (04:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Tues 16-Apr-2019 09:00 (09:00 AM) |
| US / Mountain | Tues 16-Apr-2019 10:00 (10:00 AM) |
| US / Central  | Tues 16-Apr-2019 11:00 (11:00 AM) |
| US / Eastern  | Tues 16-Apr-2019 12:00 (12:00 PM) |
| London        | Tues 16-Apr-2019 17:00 (05:00 PM) |
| Amsterdam     | Tues 16-Apr-2019 18:00 (06:00 PM) |
| Moscow        | Tues 16-Apr-2019 19:00 (07:00 PM) |
| Chennai       | Tues 16-Apr-2019 21:30 (09:30 PM) |
| Hangzhou      | Wed 17-Apr-2019 00:00 (12:00 AM) |
| Tokyo         | Wed 17-Apr-2019 01:00 (01:00 AM) |
| Sydney        | Wed 17-Apr-2019 02:00 (02:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Website%20Redesign%20Strategic%20Initiative+Meeting+2019-04-16&iso=20190416T16
* or http://www.wolframalpha.com/input/?i=04PM+UTC%2C+Apr+16%2C+2019+in+local+time

## Links

* Minutes Google Doc: https://docs.google.com/document/d/1MTyCEX2g4ohykT_0ykBlNm2rcXNuVxWH9iy5r1d5mB4/edit

## Agenda

Extracted from **outreach-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/outreach

* 🚧 (WIP) Community Contributions [#9](https://github.com/nodejs/outreach/issues/9)
* 🚧 (WIP) Community Content [#8](https://github.com/nodejs/outreach/issues/8)
* 🚧 (WIP) Community Events [#7](https://github.com/nodejs/outreach/issues/7)

## Invited

* Website Redesign Strategic Initiative Team: @nodejs/website-redesign

## Notes

The agenda comes from issues labelled with `outreach-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: https://zoom.us/j/526318636
* For those who just want to watch:
* youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

**Comment by keywordnew** [comment]
Is this on the 16th? The note says 15th.

**Comment by amiller-gh** [comment]
😬

**Comment by amiller-gh** [comment]
Getting the automated meeting generator up right now – last manual meeting 🙂

**Comment by MaedahBatool** [comment]
Awesome! 💯

**Comment by MaedahBatool** [comment]
The first link for viewing your local time and date is not working correctly. It displays data for 11th April with event status as ‘passed’.

**Comment by amiller-gh** [comment]
This is why we have automatic issue generation 😏 Fixed!

**Comment by MaedahBatool** [comment]
The meeting's minutes Google Doc link is missing. Do we have it currently?

**Comment by amiller-gh** [comment]
Updated :)
