### ISSUE TITLE
⏰ Rescheduling Time for Next Two Outreach Meetings Due to Ramadan! 

### ISSUE THREAD

**Issue by MaedahBatool** [nodejs/outreach#16]
🙌 Hey, @amiller-gh!

Due to Ramadan, Ahmad & I won't be able to attend the Outreach Meeting at the set time since we'll be fasting. 

So, if we can reschedule the time for the **next two meetings** that would be great. Otherwise, we can drop out for this month and join from the next.

The following two proposed times suits us the best.

- **12 PM UTC or 6 PM UTC**

Let me know what are your thoughts about it.

Peace!

**Comment by amiller-gh** [comment]
Updated to 6PM UTC 👍🙂
