### ISSUE TITLE
[Node.js] New Community Page

### ISSUE THREAD

**Issue by ahmadawais** [nodejs/outreach#24]
Let's build a new community page for Node.js.

- **CURRENT PAGE**: https://foundation.nodejs.org/community
- **WHERE**: Nodejs.dev/community (WIP)
- **HOW**: Let's discuss what should be on the community page and at the very least create a `community.md` file with all the content in it, which we can later design

Inspiration:

- Emberjs community page → https://emberjs.com/community
- Adam's research on the website redesign https://medium.com/the-node-js-collection/redesigning-nodejs-part-1-fac08a0e015a

Discussion from the meetings on this topic:

```
Awais: Let's reboot the Node.js community page, current examples are as follows:
foundation.nodejs.org/community
Maedah: But again first we need to define the “scope” of community. It’ll help us revamp the page the right way. If we are starting with meetups initially then we need to start working on its line of action. Rules and guidelines!
Awais: Instead of defining the scope how about we move the Community page over to Nodejs.dev and start with what we have already — improve from there.
Maedah: We can do that as well. How about making an issue like redesigning community page and ask for suggestions/feedback.
Maedah: I have scrolled the current page and I think there’s a lot which we can do from the layout to components to the entire lingo.

```

**Comment by ahmadawais** [comment]
Can we merge the [Getting Started](https://github.com/nodejs/getting-started) with this page?

**Comment by saqibameen** [comment]
I have crafted an outline of what possibly we can add to the community page. Probably we can start from this and move on to writing the content for the page.

- Introduction — A paragraph or two introducing the NodeJS community and what we do. 

- Stats — Showing # of downloads, GitHub stars, # no of events. [Foundation Page]
(https://foundation.nodejs.org/) contains some useful stats.
- Want to Contribute — Highlight different ways to get involved in the community. 
    - Contribute to the Core
    - Be a part of Community Committee
    - Report an issue

   And so on. Each link would take to separate page with a detailed description of how to get involved. For example, in the core, we can share GitHub issues link and highlight the first good issue. For Comm Comm, we can share links for meetings, documentation issues, and other ways. Also, [Get Involved Page of Nodejs.org](https://nodejs.org/en/get-involved/) contains some related material.

- Community Events: Talk about the node meetup groups around the globe, share stats, and [meetup links](https://nodejs.org/en/get-involved/node-meetups/) for them to join their nearby events.

- Grab Swag — For meetups/events grab swag from [store](https://store.nodejs.org/).

- Learning Node — For this, we can take material from [Getting Started](https://github.com/nodejs/getting-started) page.

- Stay in Touch — Link to blog and subscribe to the [Nodejs official monthly mailing list](https://us14.campaign-archive.com/home/?u=c7c2e114a827812354112c23b&id=f006b61f29). 

What are your thoughts on this folks?

**Comment by msaaddev** [comment]
I think the following can also be added and would be a good addition to the outline.

- Code of Conduct — Displays the code of conduct/community guidelines of the NodeJS community. It can be put right after Want to Contribute.

- Stuck at somewhere 
  - Need help related to the usage of NodeJS. Visit our [help](https://github.com/nodejs/help) repo.
  - Still facing an issue. Connect us on [Slack](http://nodeslackers.com/).

This can be put after the Code of Conduct section.

 - News — All the latest news of the NodeJS community will be posted here. This can be put after Community Events.

**Comment by ahmadawais** [comment]
Go ahead you two and start building the page. I'll leave my comments in the
PRs.

Saad, that Slack community link doesn't look right. Not sure if it's an
official one. So let's leave that out.

**Comment by MaedahBatool** [comment]
So, for now we are sticking with this outline and start curating a community.md file. I was thinking out loud that how about we divide these sections among us. Especially those which are not related to each other and submit PRs.

**Comment by saqibameen** [comment]
@msaaddev and I have curated some content for the community page and created a [PR](https://github.com/nodejs/outreach/pull/31) for it.

**Comment by ahmadawais** [comment]
@saqibameen @msaaddev updates?//

**Comment by saqibameen** [comment]
We have made the changes as discussed in our last meeting.

**Comment by ahmadawais** [comment]
@saqibameen please review the new pull requests when they are ready. That's how you can help. 
@msaaddev when you are done with the changes, it's a good idea to request a PR review otherwise no one knows about the progress.

I just left a review with changes requested.

**Comment by saqibameen** [comment]
I have reviewed the PR, @msaaddev is going to make the changes. The community page PR is in better shape now. Hopefully, we will be able to finalize it by the next meeting.
