### ISSUE TITLE
Node.js YouTube Channel Name

### ISSUE THREAD

**Issue by ahmadawais** [nodejs/outreach#5]
Just getting things started here. 

First thing, I'd like to improve is if we can have a channel name for Node.js

Right now it is:

```
https://www.youtube.com/channel/UCQPYJluYC_sn_Qz_XE-YbTQ
```
We can move to `nodejs` channel name.

```
https://www.youtube.com/channel/Nodejs
```

@bnb can you share how I can help with this? I'd need to get in touch with whoever manages the YouTube channel or get the admin control so I can add a Channel name.

Looking forward!

**Comment by bnb** [comment]
we currently have http://youtube.com/nodejs-foundation as an YouTube alias for the channel, but we should likely change that since that won't be a real thing anymore. I spent some time yesterday looking for how to change this but couldn't find a way, though it should be possible.

**Comment by MylesBorins** [comment]
Keep in mind that if we change it we may break a bunch of canonical urls

**Comment by ahmadawais** [comment]
Seems to have been fixed. So, I'll just close this one.
