### ISSUE TITLE
Automatic Meeting Ticket Generation

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/outreach#6]
Stub issue for me to track adding @nodejs/outreach to @nodejs/create-node-meeting-artifacts.

**Comment by MaedahBatool** [comment]
@amiller-gh any progress on this one? Do we have a meeting tomorrow or should we start next week once we have the meeting automation in place?

**Comment by amiller-gh** [comment]
We're on 🙂 https://github.com/nodejs/outreach/issues/13

Re: https://github.com/nodejs/create-node-meeting-artifacts/pull/57
